# Generated by Django 4.2.1 on 2023-06-06 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('changed_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('start_datetime', models.DateTimeField(verbose_name='Дата и время начала рассылки')),
                ('end_datetime', models.DateTimeField(verbose_name='Дата и время окончания рассылки')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('phone_code_filter', models.PositiveIntegerField(blank=True, verbose_name='Код мобильного оператора')),
                ('tag_filter', models.CharField(blank=True, max_length=50, verbose_name='Тeг')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('changed_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'В процессе'), ('SENT', 'Отправлен'), ('FAILED', 'Ошибка')], default='IN_PROGRESS', max_length=15, verbose_name='Статус')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='client.client')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mailings.mailing')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
